import type { Metadata } from "next";
import { Toaster } from 'react-hot-toast';
import { Poppins } from "next/font/google";

import "./globals.css";
import Navbar from "@/Components/HomePageComponents/Navbar";

// const inter = Inter({ subsets: ["Poppins"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
    
    <html lang="en">
      <body >
      <Toaster
  position="top-center"
  reverseOrder={false}
/>
    
        {children}</body>
    </html>
  );
}
