 const Topics: string[] = [
    "Software Engineering",
    "Machine Learning",
    "Art",
    "Photography",
    "Dance",
    "Culinary",
    "Data Science",
    "Cybersecurity",
    "Astronomy",
    "Physics",
    "Chemistry",
    "Biology",
    "Mathematics",
    "Philosophy",
    "Psychology",
    "History",
    "Geography",
    "Literature",
    "Linguistics",
    "Political Science",
    "Economics",
    "Environmental Science",
    "Sociology",
    "Anthropology",
    "Archaeology",
    "Engineering",
    "Robotics",
    "Artificial Intelligence",
    "Game Development",
    "Web Development",
    "Mobile App Development",
    "Blockchain Technology",
    "Quantum Computing",
    "Music",
    "Theater",
    "Film Studies",
    "Graphic Design",
    "Interior Design",
    "Fashion Design",
    "Architecture",
    "Ecology",
    "Genetics",
    "Marine Biology",
    "Astronautics",
    "Neuroscience",
    "Immunology",
    "Forensic Science",
    "Biotechnology",
    "Agriculture",
    "Veterinary Science",
    "Renewable Energy",
    "Urban Planning",
    "Transportation Engineering",
    "Material Science",
    "Sports Science",
    "Education",
    "Psychiatry",
    "Public Health",
    "Human Resources",
    "Marketing",
    "Journalism",
    "Creative Writing",
    "Comedy",
    "Television Production",
    "Animation",
    "Sound Engineering",
    "Tourism",
    "Hospitality Management",
    "Event Planning",
    "Horticulture"
  ];
  export default Topics;